server:
  port: 8081 # Keep your existing port

app:
  name: User Management API
  description: Advanced REST API with MongoDB and Insurance Policy Management
  version: 4.0.0
  features:
    validation: true
    error-handling: true
    mongodb: true

spring:
  application:
    name: firstapp
  data:
    mongodb:
      uri: mongodb://localhost:27017/insurance_db
      auto-index-creation: true

logging:
  level:
    com.workshop.firstapp: DEBUG
    org.springframework.data.mongodb: DEBUG